name: mataajer_saudi
version: 1.0.0+1
publish_to: none
description: Mataajer Saudi.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_messaging: ^14.2.5
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  # change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/png/
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
  uses-material-design: true

