name: mataajer_saudi
version: 1.0.0+1
publish_to: none
description: Mataajer Saudi.
environment:
  sdk: ">=2.19.2 <3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_messaging: ^14.3.0
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.6.1
  # flutter_svg: ^2.0.2
  flutter_multi_select_items: ^0.4.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.7
  firebase_storage: ^11.0.16
  file_picker: ^5.2.6
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.2
  dio: ^5.1.1
  show_up_animation: ^2.0.0
  rive: ^0.11.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/png/
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
  uses-material-design: true
