<?php 

// TIHS FILE USED TO VERIFY IF PAYMENT GATEWAY WILL WORK OR NOT TO AVOID APPLE STORE CONNECT IN-APP PURCHASE

echo "B1B(BKB(BEBAB E*B,1 BDB9B/B)"; // THE LAST CHARACTER SHOULD BE ")" TO MAKE IT VALID